<a href="https://colab.research.google.com/github/ADinng/CS6319_MachineLearning/blob/main/CS6319_machinelearning_lecture5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#lecture 05
# Numpy arrays

import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [ ]:
print(a[1:5])

[2 3 4 5]


In [ ]:
print(b[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
print(a.dtype)

int64


In [ ]:
x = a.copy()

In [ ]:
y=a.view()

In [ ]:
print(b.shape)

(2, 5)


In [ ]:
c = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
d = c.reshape(4, 3)

In [ ]:
print(d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
d = c.reshape(4, -1)

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.reshape(-1)

In [ ]:
print(b)

[1 2 3 4 5 6]


In [ ]:
b = np.array([[7,8,9],[10,11,12]])

In [ ]:
c = np.concatenate((a, b))

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
c = np.concatenate((a,b), axis=0)

In [ ]:
print(c)

[1 2 3 4 5 6]


In [ ]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])

In [ ]:
c = np.concatenate((a,b), axis=1)

In [ ]:
print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.stack((a,b), axis=1)
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
c = np.hstack((a,b))
print(c)

[1 2 3 4 5 6]


In [ ]:
d = np.vstack((a,b))
print(d)

[[1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
b = np.array_split(a, 3)
print(b)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [ ]:
# Pandas series and dataframes
import pandas as pd

In [ ]:
a = np.array([6,7,8])
s = pd.Series(a)

In [ ]:
print(a)

[6 7 8]


In [ ]:
print(s)

0    6
1    7
2    8
dtype: int64


In [ ]:
s = pd.Series(a, index=['a','z','hello'])
print(s)

a        6
z        7
hello    8
dtype: int64


In [ ]:
x = s.values
print(x)

[6 7 8]


In [ ]:
electrical grid staisility

griddata = pd.read_csv("........")
(gridvas, gridlabs)

scaler = MinMaxScaler()
gridvars = scaler.fit_transform(gridvars)

le = labelEncoder()
gridlabse = le.fit_transform(gridlabs)

classifiec = LinearSVC()
split = shuffle_split(n_split = 10, test_size = 0.2)

scores = cross_val_score(classifie, gridvars, gridlabse, scoring = "accuracy", cv = split )

UN 0.82 +_ 0.004


In [ ]:
classifiec = DecisionTreeClasifier
DT 0.84

In [ ]:
classifiec = RandomForestClassifier()
RF 0.92

In [ ]:
classifiec = SVC()
svc 0.92

In [ ]:
classifiec = KneighbourClassifier()
KN 0.85

In [ ]:
Estimat
predictor
transform


In [ ]:
linear classification
polymoniac
multiple linear regression


In [ ]:
DescisionTreeRegression
.............Classifier

Random forest
  ensemble learning


In [ ]:
kernel trick
kernel function

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
import pandas as pd
import numpy as np
housing = pd.read_csv("https://github.com/ageron/handson-ml/raw/master/datasets/housing/housing.csv")

from sklearn.model_selection import train_test_split
trainset, testset = train_test_split(housing, test_size=0.2)

traindata = trainset.drop("median_house_value", axis=1)
trainlabs = trainset["median_house_value"].copy()

trainnum = traindata.drop("ocean_proximity", axis=1)
traincat = traindata[["ocean_proximity"]]


# Combining numerical attributes
trainnum["rooms_per_household"]=trainnum["total_rooms"]/trainnum["households"]
trainnum["bedrooms_per_room"]= trainnum["total_bedrooms"]/trainnum["total_rooms"]
trainnum["population_per_household"]=trainnum["population"]/trainnum["households"]

# Handling missing values
from sklearn.impute import SimpleImputer
#  Imptuation
imputer = SimpleImputer(strategy="median")
imputer.fit(trainnum)
X = imputer.transform(trainnum)
trainnum = pd.DataFrame(X, columns=trainnum.columns)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
trainnumr = scaler.fit_transform(trainnum)

from sklearn.preprocessing import OneHotEncoder
cat_encoder = OneHotEncoder()
trainhot = cat_encoder.fit_transform(traincat).toarray()
trainnew = np.concatenate([trainnumr, trainhot], axis=1)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

linreg = LinearRegression()
linreg.fit(trainnumr, trainlabs)
predictions = linreg.predict(trainnumr)
mse = mean_squared_error(trainlabs, predictions)
rmse = np.sqrt(mse)
print("Train extended numericas LIN error = ", rmse)


Train extended numericas LIN error =  68672.7905967634


In [ ]:
# Cross-validataion
# k-fold cross-validation

from sklearn.model_selection import cross_val_score
scores = cross_val_score(linreg, trainnew, trainlabs, scoring="neg_mean_squared_error", cv=10)
# scores = cross_val_score(rfreg, trainnew, trainlabs, scoring="neg_mean_squared_error", cv=10)
# this result is better than linreg.

rmse = np.sqrt(-scores)
print("XVAL LIN RMSE mean =",rmse.mean()," stddev =",rmse.std())


XVAL LIN RMSE mean = 67929.13193437677  stddev = 2602.8838783869105


In [ ]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

split = ShuffleSplit(n_splits=10, test_size=0.2)

scores = cross_val_score(linreg, trainnew, trainlabs, scoring="neg_mean_squared_error", cv=split)
rmse=np.sqrt(-scores)
print("XVALSHUF LIN RMSE mean = ",rmse.mean()," stddev =",rmse.std())

XVALSHUF LIN RMSE mean =  67976.06422653739  stddev = 1496.2168485224943
